### DISCUSSION TITLE
Cattr installation notes

### DISCUSSION THREAD

**Discussion by vermorag** [cattr-app/server-application#163] [Show and tell]
For Cattr installation you need to use the official [Docker](https://www.docker.com/) image from [Cattr Registry](https://git.amazingcat.net/cattr/core/app/container_registry/9). Basically, all versions are tagged with `v...` tag. So, for example, you can use: `registry.git.amazingcat.net/cattr/core/app:v4.0.0-RC47`.

The docker image contains everything, except the database. So you'll need an external database or docker-compose to make it work.
So, for example, your docker-compose.yml file can look like this:
```
version: "3.9"

services:
  app:
    image: registry.git.amazingcat.net/cattr/core/app:v4.0.0-RC47  
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
    networks:
      - default
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - APP_KEY=base64:lg1m/12MHBbBpiWTXjot98Q9MP/nSzPrvLEU2beD+2Y=

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=cattr
      - MYSQL_ROOT_PASSWORD=password
    cap_add:
      - SYS_NICE
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
```

Cattr can work with percona/mysql/mariadb, so you're free to choose any. All env variables, that will be used for DB connection you can check in [config/database.php](https://github.com/cattr-app/server-application/blob/main/config/database.php#L11).
Also, it will be a good option to set APP_KEY for artisan on the compose level to persist it between restarts. Pay attention to the mounted folder `/app/storage` - it will store your screenshots and data, needed for persistence.

On first install Cattr will create an admin with the name `Admin`, login `admin@cattr.app` and password `password`, but you are free to change it with env variables `APP_ADMIN_EMAIL`, `APP_ADMIN_PASSWORD` and `APP_ADMIN_NAME`.

If you want to use HTTPS, you'll need to setup nginx on your server for proxying requests to Cattr container.
Your nginx site config can look like that:
```
server {
    listen 80;
    listen 443 ssl http2;
    listen [::]:80;
    listen [::]:443 ssl http2;
    server_name cattr.app www.cattr.app;

    ssl_certificate /etc/letsencrypt/live/cattr.app/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/cattr.app/privkey.pem; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    location /  {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Real-Port $server_port;
        proxy_set_header X-Real-Scheme $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
     }
}
```

That's all. You can ask any questions about Cattr installation in the thread.
