### DISCUSSION TITLE
How can i Install Cattr in May 2024?

### DISCUSSION THREAD

**Discussion by airsay** [cattr-app/server-application#283] [General]
It looks like the documentation on docs.cattr.app is outdated. The Easy and advanced install both failed for me. So I visited https://git.amazingcat.net/cattr/core/app and followed the installation instructions there. I am getting a 500 Error. Here's what I have done so far

1. Spun up a Fresh instance of Debian 11
2. Update repos and upgraded preinstalled apps.
 `sudo apt update && sudo apt upgrade -y`
3. Installed basic prerquisites
`sudo apt install git wget sudo curl wget gnupg gnupg2 sb-release apt-transport-https ca-certificates software-properties-common -y`
4. Installed MySQL 8.0
```
#Install MySQL
wget https://dev.mysql.com/get/mysql-apt-config_0.8.30-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.30-1_all.deb
sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
sudo sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
sudo apt update
sudo apt install mysql-server -y
sudo apt install php8.2 php8.2-{bcmath,bz2,intl,gd,mbstring,mysql,zip,curl,xml} -y
sudo apt install nginx php8.2-fpm -y
```

I noticed that running `sudo apt install nginx php8.2-fpm -y` resulted in Apache2 getting installed, causing nginx to fail when I attempt to start it using` systemctl restart nginx`. So I uninstalled Apache as shown below

5. Uninstall Apache
```
sudo systemctl stop apache2
sudo apt-get purge apache2 apache2-utils apache2-bin apache2.2-common
sudo apt-get remove apache2
sudo apt-get autoremove
sudo rm -rf /etc/apache2
sudo rm -rf /var/www
sudo rm -rf /var/log/apache2
sudo rm -rf /var/lib/apache2
```

6. Restarted nginx and php8.2-fpm
```
# Restart services to apply changes
sudo systemctl restart nginx
sudo systemctl restart php8.2-fpm
```

7.Installed Node.js v18 (the app does not support versions greater than v18)
```
# Install Node.js
#curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install -y nodejs
```

8. Installed Yarn
```
#install Yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn
```

9. Installed Composer
```
#install Composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer
```
10. Cloned the repo
```
cd /opt
git clone https://git.amazingcat.net/cattr/core/app.git
cd app
```

11. Started install (which went swimmingly)
```
sudo composer install && sudo php artisan key:generate && sudo yarn
sudo php artisan migrate --seed --seeder=InitialSeeder
sudo php artisan cattr:make:admin
npm run prod

```

Snippet from My nginx.conf (`/etc/nginx/nginx.conf`)
```
server {
    listen 80;
    server_name 10.10.10.218;
    #root /var/www/html;
    root /opt/app/public;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}

```

When I eventually visit the URL at http://10.10.10.218, I get an Error 500 with almost nothing to go on with. I have checked the
`storage/logs/laravel.log` and I only see an older error message about M`ix manifest not found at: /opt/app/public/mix-manifest.json` which I have since resolved. 

I have looked at the Chrome browser console and the errors there don't make any sense as I don't even know what to look for even though I see a handful of errors mostly about
`WebSocket connection to wss://10.10.10.218/app/cattr?protocol=7&client=js&version=8.4.8-rc2&flash=false`

Can anyone suggest how to troubleshoot this?

**Comment by vermorag** [comment]
Hello. Try to run `yarn prod` instead of `npm run prod`.

**Reply by airsay** [reply]
`yarn prod` doesn't seem to fix it. I still get Error 500

**Reply by airsay** [reply]
Just performed a fresh install, runinng `yarn prod` and still running into the same Error 500.

**Comment by airsay** [comment]
I also can't seem to get the docker version going. I see the cattr-frontend-1 in an _unhealthy_ state

Docker compose file as downloaded from (https://git.amazingcat.net/cattr/core/docker/-/releases/permalink/latest/downloads/compose)

```
version: '3.9'

services:
  backend: &app
    image: registry.git.amazingcat.net/cattr/core/cattr-backend:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend_public:/app/public
      - backend_storage:/app/storage
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q "http://127.0.0.1:8090/status"']
      interval: 10s
      timeout: 2s

  queue:
    <<: *app
    command: ['queue']
    depends_on:
      backend:
        condition: service_healthy
    healthcheck: {}

  cron:
    <<: *app
    command: ['cron']
    depends_on:
      backend:
        condition: service_healthy
    healthcheck: {}

  frontend:
    image: registry.git.amazingcat.net/cattr/core/cattr-frontend:latest
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - backend_public:/backend
    ports:
      - "127.0.0.1:8089:8080"
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail -LI http://127.0.0.1:8080 -o /dev/null -w "%{http_code}\n" -s > /dev/null']
      interval: 10s
      timeout: 2s

  db:
    image: percona:latest
    environment:
      - MYSQL_DATABASE=cattr
      - MYSQL_ROOT_PASSWORD=password
    cap_add:
      - SYS_NICE
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

volumes:
  backend_public: {}
  backend_storage: {}
  database: {}
```

after which I run `docker-compose -p cattr up -d` and `docker-compose -p cattr run --rm -it backend install`

When I visit my server's ip address http://10.10.10.219 I get a `ERR_CONNECTION_REFUSED` error.
