### DISCUSSION TITLE
The admin user does not have admin rights

### DISCUSSION THREAD

**Discussion by VincentSC** [cattr-app/server-application#299] [Q&A]
I just installed using docker-compose and nginx-proxy. See below for what I used, which went flawlessly.

PROBLEM: The admin-user does not have the menu-item for [the company-setting page as shown in the documentation](https://docs.cattr.app/#/en/integrations/?id=redmine-global). 

During install it shows:
```
app-1  | Route POST:/instance not found
app-1  | Administrator with email [XXX] was created successfully
app-1  | s6-rc: info: service create-admin successfully started
app-1  | s6-rc: info: service laravel: starting
app-1  | s6-rc: info: service laravel successfully started
app-1  | s6-rc: info: service queue: starting
app-1  | s6-rc: info: service queue successfully started
app-1  | s6-rc: info: service legacy-services: starting
app-1  | s6-rc: info: service legacy-services successfully started
```

The one undocumented thing is APP_KEY. I suppose to change that, but I'm only guessing how to do this. So my only guess was that I should have left that as it was.
I also see different APP_KEY entries in the [documentation](https://docs.cattr.app/#/en/getting-started/?id=installation-linux-deb) and in the [Dockerfile](https://git.amazingcat.net/cattr/core/app/-/blob/main/Dockerfile?ref_type=heads).  I tried the one from git and the one from the documentation, and that did not solve it. I simply don't know what it does.

**Did anybody encounter the same problem and knows what to do?**

**What does APP_KEY do?**

```
services:
  app:
    image: registry.git.amazingcat.net/cattr/core/app:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./volumes/app_storage:/app/storage
    networks:
      - nginx-proxy
      - default
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
      # Admin user only created on initial run with the following credentials, change them if needed
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
      - APP_ADMIN_NAME=${APP_ADMIN_NAME}

  db:
    image: percona:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=cattr
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    cap_add:
      - SYS_NICE
    volumes:
      - ./volumes/percona:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--password=${DB_PASSWORD}', '-u', 'root']
      timeout: 20s
      retries: 10
    networks:
      - default


networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy
```

And (emptied) .env:
```
COMPOSE_PROJECT_NAME=cattr
DOMAIN=
DB_PASSWORD=
APP_ADMIN_EMAIL=
APP_ADMIN_PASSWORD=
APP_ADMIN_NAME=Admin
APP_KEY=
```
