### ISSUE TITLE
Docker install not working

### ISSUE THREAD

**Issue by DaWe35** [cattr-app/server-application#111]
I installed the docker app following your official documentation. I see only 8089 port is opened, but I get "connection refused" when trying to connect.

**Comment by DanilShapilov** [comment]
@DaWe35 Hi. For now we have outdated documentation and not working deploy for desktop app.  
As an option you can build latest version yourself. Just clone current repo and run `docker compose up`.  

Also **if above didn't work**, you can try with this docker-compose
```yml
version: '3.9'

services:
    app:
        build: .
        depends_on:
            db:
                condition: service_healthy

        ports:
            - 80:80
    db:
        image: percona:latest
        environment:
            - MYSQL_DATABASE=cattr
            - MYSQL_ROOT_PASSWORD=password
        cap_add:
            - SYS_NICE
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--password=password', '-u', 'root']
            timeout: 20s
            retries: 10

volumes:
    database: {}

```

As for desktop client here are the latest version v3.0.0-RC10 (or you can build it yourself):  

Linux: https://git.amazingcat.net/cattr/desktop/desktop-application/-/jobs/13523/artifacts/browse/target/

Mac: https://git.amazingcat.net/cattr/desktop/desktop-application/-/jobs/13524/artifacts/browse/target/

Windows: https://git.amazingcat.net/cattr/desktop/desktop-application/-/jobs/13556/artifacts/browse/target/

**Comment by x4IPx** [comment]
If I use `git clone git@github.com:cattr-app/server-application.git` and run `docker compose up`
 I get an error:

```
#0 13.76 ➤ YN0001: │ Error: vue-color@npm:2.8.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-22bea4f4'
#0 13.76 ➤ YN0013: │ xtend@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
#0 13.77 ➤ YN0001: │ Error: pako@npm:1.0.11: ENOSPC: no space left on device, mkdir '/tmp/xfs-583ce56e'
#0 13.77 ➤ YN0013: │ y18n@npm:5.0.8 can't be found in the cache and will be fetched from the remote registry
#0 13.78 ➤ YN0001: │ Error: workbox-precaching@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-77500c1c'
#0 13.78 ➤ YN0013: │ yallist@npm:2.1.2 can't be found in the cache and will be fetched from the remote registry
#0 13.78 ➤ YN0001: │ Error: workbox-window@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-8a25294b'
#0 13.78 ➤ YN0013: │ yallist@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
#0 13.78 ➤ YN0001: │ Error: workbox-broadcast-update@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-0dec6be2'
#0 13.80 ➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
#0 13.82 ➤ YN0001: │ Error: pusher-js@npm:8.0.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-cb6e789a'
#0 13.82 ➤ YN0001: │ Error: whatwg-url@npm:11.0.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-c7a2b403'
#0 13.82 ➤ YN0001: │ Error: workbox-core@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-549a92b1'
#0 13.82 ➤ YN0001: │ Error: workbox-google-analytics@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-60b4efe8'
#0 13.82 ➤ YN0001: │ Error: workbox-range-requests@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-230b342f'
#0 13.82 ➤ YN0013: │ yaml@npm:1.10.2 can't be found in the cache and will be fetched from the remote registry
#0 13.83 ➤ YN0013: │ yargs-parser@npm:20.2.9 can't be found in the cache and will be fetched from the remote registry
#0 13.83 ➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
#0 13.83 ➤ YN0013: │ yargs@npm:17.7.1 can't be found in the cache and will be fetched from the remote registry
#0 13.83 ➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
#0 13.83 ➤ YN0001: │ Error: wrappy@npm:1.0.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-16e388ab'
#0 13.83 ➤ YN0001: │ Error: ws@npm:8.13.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-c7e62be5'
#0 13.84 ➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
#0 13.84 ➤ YN0001: │ Error: workbox-cacheable-response@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-b4418ecb'
#0 13.84 ➤ YN0001: │ Error: workbox-navigation-preload@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-ad4351be'
#0 13.84 ➤ YN0001: │ Error: xmlchars@npm:2.2.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-6e3e86ef'
#0 13.84 ➤ YN0001: │ Error: xtend@npm:4.0.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-2514c3cd'
#0 13.84 ➤ YN0001: │ Error: ws@npm:7.5.9: ENOSPC: no space left on device, mkdir '/tmp/xfs-f7f6f77a'
#0 13.85 ➤ YN0001: │ Error: workbox-build@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-101d9f86'
#0 13.86 ➤ YN0001: │ Error: yallist@npm:3.1.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-fd4b3e36'
#0 13.86 ➤ YN0001: │ Error: yallist@npm:2.1.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-aef65e88'
#0 13.87 ➤ YN0001: │ Error: xml-name-validator@npm:4.0.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-b6ed3fcb'
#0 13.87 ➤ YN0001: │ Error: y18n@npm:5.0.8: ENOSPC: no space left on device, mkdir '/tmp/xfs-78f82ec2'
#0 13.87 ➤ YN0001: │ Error: yn@npm:3.1.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-415c411f'
#0 13.88 ➤ YN0001: │ Error: yallist@npm:4.0.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-573348de'
#0 13.88 ➤ YN0001: │ Error: whatwg-url@npm:10.0.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-b5c0df48'
#0 13.89 ➤ YN0001: │ Error: yaml@npm:1.10.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-9cf1e8fd'
#0 13.91 ➤ YN0001: │ Error: yargs-parser@npm:21.1.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-706dccb3'
#0 13.93 ➤ YN0001: │ Error: yocto-queue@npm:0.1.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-7a5b4d2e'
#0 14.01 ➤ YN0001: │ Error: yargs-parser@npm:20.2.9: ENOSPC: no space left on device, mkdir '/tmp/xfs-8a573b01'
#0 14.09 ➤ YN0001: │ Error: webpack-dev-server@npm:4.11.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-541c2d95'
#0 14.11 ➤ YN0001: │ Error: yargs@npm:17.7.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-d522bdbc'
#0 14.12 ➤ YN0001: │ Error: validator@npm:13.9.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-560427af'
#0 14.18 ➤ YN0001: │ Error: workbox-webpack-plugin@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-0e0bbb1b'
#0 14.36 ➤ YN0001: │ Error: webpackbar@npm:5.0.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-6e53fc6d'
#0 14.72 ➤ YN0001: │ Error: xstate@npm:4.37.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-0519b4cb'
#0 14.80 ➤ YN0001: │ Error: webpack@npm:5.80.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-453c045d'
#0 14.80 ➤ YN0001: │ Error: workbox-strategies@npm:6.5.4: ENOSPC: no space left on device, mkdir '/tmp/xfs-98a84fb2'
#0 14.88 ➤ YN0001: │ Error: vee-validate@npm:3.4.15: ENOSPC: no space left on device, mkdir '/tmp/xfs-a2b7caff'
#0 14.97 ➤ YN0001: │ Error: vue-kanban@npm:1.8.0: ENOSPC: no space left on device, mkdir '/tmp/xfs-cbec0be4'
#0 15.09 ➤ YN0001: │ Error: mapbox-gl@npm:2.14.1: ENOSPC: no space left on device, mkdir '/tmp/xfs-783b2823'
#0 15.27 ➤ YN0001: │ Error: vue@npm:2.7.14: ENOSPC: no space left on device, mkdir '/tmp/xfs-acc55c3f'
#0 15.40 ➤ YN0001: │ Error: vue-loading-skeleton@npm:1.1.9: ENOSPC: no space left on device, mkdir '/tmp/xfs-fd69dc54'
#0 15.73 ➤ YN0001: │ Error: typescript@npm:5.0.2: ENOSPC: no space left on device, mkdir '/tmp/xfs-5e81961f'
#0 15.73 ➤ YN0000: └ Completed in 13s 922ms
#0 15.73 ➤ YN0000: Failed with errors in 14s 225ms
```

```yml
version: '3.9'

services:
    app:
        build: .
        depends_on:
            db:
                condition: service_healthy

        ports:
            - 80:80
    db:
        image: percona:latest
        environment:
            - MYSQL_DATABASE=cattr
            - MYSQL_ROOT_PASSWORD=password
        cap_add:
            - SYS_NICE
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--password=password', '-u', 'root']
            timeout: 20s
            retries: 10

volumes:
    database: {}

```
Doesn't work either
