### ISSUE TITLE
How to launch cattr via docker compose 

### ISSUE THREAD

**Issue by x4IPx** [cattr-app/server-application#85]
Can't run cattr via docker compose .

```
 $docker version
Client: Docker Engine - Community
 Version:           24.0.0
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        98fdcd7
 Built:             Mon May 15 18:49:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.0
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       1331b8c
  Built:            Mon May 15 18:49:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
$docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```
```
$docker compose version
Docker Compose version v2.18.0
```
![Screenshot_56](https://github.com/cattr-app/server-application/assets/58852253/782cda76-d2ad-46be-9f41-02c4fd3946d3)

I use the chapter "Getting started" : https://docs.cattr.app/#/en/getting-started/
```
wget https://git.amazingcat.net/cattr/core/docker/-/releases/permalink/latest/downloads/installer -O cattr.sh
bash cattr.sh
````
On request Full URL to backend (API) application (example: http://cattr.acme.corp/):
I write
```
http://cattr.acme.corp/
```

As a result I get an error  

  ```
In Connection.php line 760:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cattr.role' doesn't exist (SQL: select * from `role` where (`id` = 1) and `role`.`deleted_at` is null limit 1)


In Exception.php line 18:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cattr.role' doesn't exist


In PDOStatement.php line 117:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cattr.role' doesn't exist
  ```

![Screenshot_58](https://github.com/cattr-app/server-application/assets/58852253/cac889fe-6896-450b-a4d2-5906eed35191)

**Comment by x4IPx** [comment]
In general, I want to prepare a working docker-compose.yml that can be quickly launched.
For example, now I am using a 2 year old solution: https://hub.docker.com/r/amazingcat/cattr

**Comment by x4IPx** [comment]
Maybe the error is that the cattr.sh script should use `docker compose up` and not `docker-compose`

**Comment by Ibrar-Akhtar** [comment]
@x4IPx Hi, I'm not very familiar with docker, Can you help me with the given issue:
I have run `docker compose up -d` in the root directory but no container started running. The only thing I got was a single image there and I was not able to run that image.
Thanks!

**Comment by x4IPx** [comment]
> @x4IPx Hi, I'm not very familiar with docker, Can you help me with the given issue: I have run `docker compose up -d` in the root directory but no container started running. The only thing I got was a single image there and I was not able to run that image. Thanks!

Hello.
Unfortunately, I myself can not run cattr through docker compose

**Comment by Ibrar-Akhtar** [comment]
> > @x4IPx Hi, I'm not very familiar with docker, Can you help me with the given issue: I have run `docker compose up -d` in the root directory but no container started running. The only thing I got was a single image there and I was not able to run that image. Thanks!
> 
> Hello. Unfortunately, I myself can not run cattr through docker compose

ok thanks for your response.
I hope cattr team will make it workable in the future.
@amazing-cat I have spent weeks for making cattr-setup and deployment with docker but got no luck. I was having a situation like bad-fixes.

**Comment by x4IPx** [comment]
> ok thanks for your response. I hope cattr team will make it workable in the future. @amazing-cat I have spent weeks for making cattr-setup and deployment with docker but got no luck. I was having a situation like bad-fixes.

You can try to run `docker-compose.yml`

```
version: "3.3"
services:
  cattr:
    image: amazingcat/cattr
    restart: always
    ports:
      - "80:80"
    volumes:
      - cattr-db:/var/lib/mysql
      - cattr-config:/app/backend/bootstrap/cache
      - cattr-screenshots:/app/backend/storage/app/uploads/screenshots
      - cattr-ssl:/etc/letsencrypt
    environment:
     FRONTEND_DOMAIN: cattr.test1.test2
     ADMIN_MAIL: it@yourdomen.ru
     FRONTEND_APP_URL: http://cattr.test1.test2
     HTTPS: "false"
     MAIL_FROM_ADDRESS: cattr@yourdomen.ru
volumes:
 cattr-db:
 cattr-config:
 cattr-screenshots:
 cattr-ssl:
```

But this is a very old but stable version  : https://hub.docker.com/r/amazingcat/cattr/tags
